#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# french keyboard layout
setxkbmap fr &

# clicks faster when holding down a key (useful in vim to go up/down/left/right)
xset r rate 300 50

# normal mouse cursor in bspwm
xsetroot -cursor_name left_ptr &

# starts the compositor
picom --experimental-backends &

# restores the last pywal color scheme and wallpaper
wal -R &

# notifications daemon
dunst &

# blue light 'filter'
xflux -l 44.0169 -g 4.81 &

# numberpad
numlockx &

# setting up the screen locker
xss-lock -disco -- env xsecurelock &

exec bspwm


