#! /bin/sh

# Keyboard shortcuts
pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart
$HOME/.config/polybar/launch.sh &
$HOME/.config/bspwm/caps.sh &

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap          15

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config bottom_padding 0
bspc config top_padding -45

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
